/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package camping.org;

import static camping.org.RegisterFrame.URL;
import static camping.org.RegisterFrame.USER;
import static camping.org.RegisterFrame.PASS;
import static camping.org.wildlifecamps.currentuser;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author harish
 */
public class treks extends javax.swing.JFrame {

    /**
     * Creates new form treks
     */
    static String currentuser = null;
    public treks(String s) {
        initComponents();
        currentuser = s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        bookt2 = new javax.swing.JButton();
        bookt1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        home = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu1 = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu4 = new javax.swing.JMenu();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(java.awt.Color.yellow);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("\tThe Everest Base Camp Trek\nThe Everest Base Camp Trek, is one of the most famous\n Trek in Nepal, which is famous for its fantastic mountain\n peaks and the beauty on the hills. Most of the places to \nthis spot go through ridges and trails, but you would \nhave ample space to rest and have meal on your way. \nAnd one of the best things about this place is that \nyou don’t have to worry about being lost, as you can \nask anybody for the next village. The people here are \nvery friendly and offer help and support even to \nstrangers. The people who live here are mostly \nshepherds and understand English; \nsome even speak it fluently. \nAmount - Rs 60,000/-");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(140, 680, 410, 220);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(java.awt.Color.yellow);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("\t\tTarsar Marsar\nMost people flock to Tarsar Marsar in August, when the flora \nis at its best. Not just that, most people fail to notice the \n5 best highlights of this trek too, which is why it is so \nunderrated.On the Tarsar Marsar trek, there are three such \nlakes, and you camp right beside two of them — Tarsar and \nSundersar.\nAmount - Rs. 25,500 /-");
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 160, 440, 120);

        bookt2.setBackground(java.awt.Color.yellow);
        bookt2.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        bookt2.setText("BOOK");
        bookt2.setOpaque(true);
        bookt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookt2MouseClicked(evt);
            }
        });
        bookt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookt2ActionPerformed(evt);
            }
        });
        getContentPane().add(bookt2);
        bookt2.setBounds(320, 910, 90, 29);

        bookt1.setBackground(java.awt.Color.yellow);
        bookt1.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        bookt1.setText("BOOK");
        bookt1.setOpaque(true);
        bookt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookt1MouseClicked(evt);
            }
        });
        bookt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookt1ActionPerformed(evt);
            }
        });
        getContentPane().add(bookt1);
        bookt1.setBounds(190, 320, 80, 28);

        jLabel1.setBackground(java.awt.Color.yellow);
        jLabel1.setFont(new java.awt.Font("URW Chancery L", 1, 50)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TREKS");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 10, 336, 72);

        jLabel2.setIcon(new javax.swing.ImageIcon("/home/harish/project/everestbasecamp.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 520, 770, 450);

        jLabel3.setIcon(new javax.swing.ImageIcon("/home/harish/project/tarsarmarsar.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 880, 620);

        jMenuBar1.setBackground(new java.awt.Color(249, 240, 247));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenuBar1.setForeground(new java.awt.Color(12, 9, 2));
        jMenuBar1.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N

        home.setBackground(new java.awt.Color(242, 241, 237));
        home.setForeground(new java.awt.Color(20, 17, 7));
        home.setText(" HOME");
        home.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        home.setMaximumSize(new java.awt.Dimension(90, 32767));
        home.setPreferredSize(new java.awt.Dimension(60, 19));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        home.add(jSeparator1);

        jMenuBar1.add(home);

        jMenu1.setBackground(new java.awt.Color(250, 249, 244));
        jMenu1.setForeground(new java.awt.Color(12, 10, 4));
        jMenu1.setText("GALLERY");
        jMenu1.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu1.setMaximumSize(new java.awt.Dimension(100, 32767));
        jMenu1.setPreferredSize(new java.awt.Dimension(60, 19));
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.add(jSeparator2);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(228, 226, 214));
        jMenu2.setForeground(new java.awt.Color(9, 7, 2));
        jMenu2.setText("BOOKING");
        jMenu2.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jMenu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu2.setMaximumSize(new java.awt.Dimension(100, 32767));
        jMenu2.setPreferredSize(new java.awt.Dimension(60, 19));

        jMenuItem1.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jMenuItem1.setText("WILDLIFE CAMPS");
        jMenuItem1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jMenuItem2.setText("TREKS");
        jMenuItem2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jMenuItem3.setText("INTERNATIONAL CAMPS");
        jMenuItem3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem3MouseClicked(evt);
            }
        });
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);
        jMenu2.add(jSeparator3);

        jMenuBar1.add(jMenu2);

        jMenu4.setForeground(new java.awt.Color(33, 29, 22));
        jMenu4.setText("YOUR BOOKINGS AND CANCELLATION");
        jMenu4.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jMenu4.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jMenu4.setMaximumSize(new java.awt.Dimension(315, 32767));
        jMenu4.add(jSeparator4);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookt1ActionPerformed

    private void bookt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookt2ActionPerformed

    private void bookt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookt1MouseClicked
        // TODO add your handling code here:
        Connection conn = null;
            PreparedStatement pstmt = null;
            Statement stmt = null;
            String book_id = "t1";
            try
            {
                System.out.println("current user is:"+currentuser);
                
                Class.forName("com.mysql.jdbc.Driver");
                conn = DriverManager.getConnection(URL,USER,PASS);
                pstmt = conn.prepareStatement("update `userData` set booking_id=? where username = '" +currentuser+"';");
                pstmt.setString(1,book_id);
                pstmt.executeUpdate();
                
                stmt = conn.createStatement();
                ResultSet rs = stmt.executeQuery("select booking_id from userData where username = '"+currentuser+"';");
                rs.next();
                String bid = rs.getString(1);
                
                String query = "insert into bookings values (?,?);";
                pstmt =  conn.prepareStatement(query);
                pstmt.setString(1,currentuser);
                pstmt.setString(2,bid);
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null, 
                        "booking confirmed",
                        "Welcome!", 
                        JOptionPane.INFORMATION_MESSAGE);
                System.out.println("booking confirmed and booking id updated");
            }
            catch(SQLException se)
            {
                se.printStackTrace();
            }
            catch(Exception e){
      //Handle errors for Class.forName
            e.printStackTrace();
            }
    }//GEN-LAST:event_bookt1MouseClicked

    private void bookt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookt2MouseClicked
        // TODO add your handling code here:
            Connection conn = null;
            PreparedStatement pstmt = null;
            Statement stmt = null;
            String book_id = "t2";
            try
            {
                System.out.println("current user is:"+currentuser);
                
                Class.forName("com.mysql.jdbc.Driver");
                conn = DriverManager.getConnection(URL,USER,PASS);
                pstmt = conn.prepareStatement("update `userData` set booking_id=? where username = '" +currentuser+"';");
                pstmt.setString(1,book_id);
                pstmt.executeUpdate();
                stmt = conn.createStatement();
                ResultSet rs = stmt.executeQuery("select booking_id from userData where username = '"+currentuser+"';");
                rs.next();
                String bid = rs.getString(1);
                
                String query = "insert into bookings values (?,?);";
                pstmt =  conn.prepareStatement(query);
                pstmt.setString(1,currentuser);
                pstmt.setString(2,bid);
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null, 
                        "booking confirmed",
                        "Welcome!", 
                        JOptionPane.INFORMATION_MESSAGE);
                System.out.println("booking confirmed and booking id updated");            
            }
            catch(SQLException se)
            {
                se.printStackTrace();
            }
            catch(Exception e){
      //Handle errors for Class.forName
            e.printStackTrace();
            }
        
    }//GEN-LAST:event_bookt2MouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        dispose();
        new MyProjectFrame().setVisible(true);
    }//GEN-LAST:event_homeMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        dispose();
        new gallery(currentuser).setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new wildlifecamps(currentuser).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem3MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        dispose();
        new intrcamps(currentuser).setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        
    }    
      private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
         dispose();
        new yourbooking(currentuser).setVisible(true);
    }                             
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(treks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(treks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(treks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(treks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new treks(currentuser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookt1;
    private javax.swing.JButton bookt2;
    private javax.swing.JMenu home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
