/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package camping.org;
import java.sql.*;
import static camping.org.RegisterFrame.URL;
import static camping.org.RegisterFrame.USER;
import static camping.org.RegisterFrame.PASS;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author harish
 */
public class yourbooking extends javax.swing.JFrame {

    /**
     * Creates new form yourbooking
     */static String currentname =  null;
            static int currentamount = 0;
    static String currentuser = null;
    public yourbooking(String s) {
        initComponents();
        currentuser = s;
        /*namebooked.setText();
        Amountbooked.setText();*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        billdisplay = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        home = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu1 = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu4 = new javax.swing.JMenu();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setBackground(java.awt.Color.magenta);
        jButton1.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jButton1.setText("DELETE");
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(java.awt.Color.magenta);
        jLabel1.setFont(new java.awt.Font("URW Chancery L", 1, 48)); // NOI18N
        jLabel1.setText("YOUR BOOKING AND CANCELLATION");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);

        jButton2.setBackground(java.awt.Color.magenta);
        jButton2.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jButton2.setText("SHOW");
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME OF CAMP", "AMOUNT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        billdisplay.setBackground(java.awt.Color.white);
        billdisplay.setFont(new java.awt.Font("URW Gothic L", 1, 24)); // NOI18N
        billdisplay.setOpaque(true);

        jMenuBar1.setBackground(new java.awt.Color(249, 240, 247));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenuBar1.setForeground(new java.awt.Color(12, 9, 2));
        jMenuBar1.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N

        home.setBackground(new java.awt.Color(242, 241, 237));
        home.setForeground(new java.awt.Color(20, 17, 7));
        home.setText(" HOME");
        home.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        home.setMaximumSize(new java.awt.Dimension(90, 32767));
        home.setPreferredSize(new java.awt.Dimension(60, 19));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        home.add(jSeparator1);

        jMenuBar1.add(home);

        jMenu1.setBackground(new java.awt.Color(250, 249, 244));
        jMenu1.setForeground(new java.awt.Color(12, 10, 4));
        jMenu1.setText("GALLERY");
        jMenu1.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu1.setMaximumSize(new java.awt.Dimension(100, 32767));
        jMenu1.setPreferredSize(new java.awt.Dimension(60, 19));
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.add(jSeparator2);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(228, 226, 214));
        jMenu2.setForeground(new java.awt.Color(9, 7, 2));
        jMenu2.setText("BOOKING");
        jMenu2.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jMenu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu2.setMaximumSize(new java.awt.Dimension(100, 32767));
        jMenu2.setPreferredSize(new java.awt.Dimension(60, 19));

        jMenuItem1.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jMenuItem1.setText("WILDLIFE CAMPS");
        jMenuItem1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jMenuItem2.setText("TREKS");
        jMenuItem2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jMenuItem3.setText("INTERNATIONAL CAMPS");
        jMenuItem3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem3MouseClicked(evt);
            }
        });
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);
        jMenu2.add(jSeparator3);

        jMenuBar1.add(jMenu2);

        jMenu4.setForeground(new java.awt.Color(33, 29, 22));
        jMenu4.setText("YOUR BOOKINGS AND CANCELLATION");
        jMenu4.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jMenu4.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jMenu4.setMaximumSize(new java.awt.Dimension(315, 32767));
        jMenu4.add(jSeparator4);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                            .addComponent(billdisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(billdisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        dispose();
        new MyProjectFrame().setVisible(true);
    }//GEN-LAST:event_homeMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        dispose();
        new gallery(currentuser).setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new wildlifecamps(currentuser).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        dispose();
        new treks(currentuser).setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem3MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        dispose();
        new intrcamps(currentuser).setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            String bookingid= null;
            Connection conn = null,con=null;
            Statement stmt = null,stmt1=null;
            int sum = 0;
            try{
            Class.forName("com.mysql.jdbc.Driver");
            System.out.println("Connecting to a selected database...");
            conn = DriverManager.getConnection(URL,USER,PASS);
            System.out.println("Connected database successfully...");
            stmt = conn.createStatement();
            String query = " select booking_id from bookings where username = '"+currentuser+"';";
            
            ResultSet rs = stmt.executeQuery(query);
            
            while(rs.next())
            {
            bookingid = rs.getString(1);
            con = DriverManager.getConnection(URL,USER,PASS);
            stmt1 = con.createStatement();
            ResultSet rs1 = stmt1.executeQuery("select amount from amount where booking_id = '"+bookingid+"';");
            
            rs1.next();
            
            sum += rs1.getInt(1);
            }
            // we have the total amount for the user in the sum variable
            System.out.println("The total Amount is:"+sum);
           
            
            displaycontent(jTable2,currentuser);
            
            billdisplay.setText("Total bill is:Rs."+String.valueOf(sum));

        }
            catch(SQLException se){
      //Handle errors for JDBC
            se.printStackTrace();
            }catch(Exception e){
      //Handle errors for Class.forName
            e.printStackTrace();
            }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          Connection conn = null;
            Statement stmt = null;
            
            try
            {
                System.out.println("current user is:"+currentuser);
                
                Class.forName("com.mysql.jdbc.Driver");
                conn = DriverManager.getConnection(URL,USER,PASS);
                stmt = conn.createStatement();
                stmt.executeQuery("delete from bookings where username in '" +currentuser+"';");
                
                stmt.executeQuery("update userData set booking_id = null where username = '"+currentuser+"';");
                
                JOptionPane.showMessageDialog(null, 
                        "bookings deleted",
                        "Welcome!", 
                        JOptionPane.INFORMATION_MESSAGE);
                System.out.println("booking confirmed and booking id updated");
            }
            catch(SQLException se)
            {
                se.printStackTrace();
            }
            catch(Exception e){
      //Handle errors for Class.forName
            e.printStackTrace();
            }
            
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void displaycontent(JTable table,String user)
    {
        Connection conn = null;
        PreparedStatement pstmt = null;
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(URL,USER,PASS);
            pstmt = conn.prepareStatement("select i.name , a.amount from information i , amount a ,bookings b\n" +
            "where a.booking_id = i.booking_id and i.booking_id = b.booking_id and a.booking_id = b.booking_id and b.username = '"+user+"' ;");
            ResultSet rs = pstmt.executeQuery();
            DefaultTableModel model = (DefaultTableModel)table.getModel();
            Object row[];
            while(rs.next())
            {
                row  = new Object[2];
                row[0] = rs.getString(1);
                row[1] = rs.getInt(2);
                model.addRow(row);
                
            }
            
        }
        catch(SQLException ex)
                {
                    ex.printStackTrace();
                }
        catch(Exception e){
      //Handle errors for Class.forName
            e.printStackTrace();
            }
        
    }
    
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yourbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yourbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yourbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yourbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
           
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new yourbooking(currentuser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel billdisplay;
    private javax.swing.JMenu home;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
